name: PyInstaller CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Create venv
      run: |
        python -m venv .venv
        .venv/Scripts/activate.bat

    - name: Install dependencies
      run: |
        .venv/Scripts/activate.bat
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Install Requirements
      run: |
        .venv/Scripts/activate.bat
        pip install -r requirements.txt




    - name: Build executable
      run: |
        .venv/Scripts/activate.bat
        pip show customtkinter
        pyinstaller --noconfirm --onedir --windowed --add-data 'C:\hostedtoolcache\windows\python\3.9.13\x64\lib\site-packages\customtkinter;customtkinter/' --add-data "cfg;cfg/" --add-data "scores;scores/" --add-data "rankings;rankings/" "main.py"


    - name: Create directory structure
      shell: cmd
      run: |
          mkdir dist\main\source
          move dist\main\* dist\main\source\
          rmdir /S /Q dist\main\cfg dist\main\rankings dist\main\scores
          move cfg dist\main\rankings dist\main\scores dist\main\

    - name: Create shortcut
      run: |
          $shortcutPath = "dist/main/main.lnk"
          $targetPath = "$(pwd)/dist/main/source/main.exe"
          $shell = New-Object -ComObject WScript.Shell
          $shortcut = $shell.CreateShortcut($shortcutPath)
          $shortcut.TargetPath = $targetPath
          $shortcut.Save()

    - name: Create ZIP artifact
      run: Compress-Archive -Path dist/main -DestinationPath artifact.zip


    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: artifact.zip